server:
  port: 8080

spring:
  datasource:
    username: root
    password: Cnfc515053
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

search:
  user-agent: "HeliontSearchBot"
  referrer: "https://ya.ru/"
  request-delay: 5000  # Время задержки между запросами в миллисекундах

indexing-settings:
  sites:
    - url: "http://www.playback.ru/"
      name: "PlayBack.Ru"
    - url: "https://volochek.life/"
      name: "Volochek.life"